### ISSUE TITLE
Installation and Usage

### ISSUE THREAD

**Issue by jacoblockett** [Astro36/korean-dictionary#1]
Hi! I'm having the hardest time trying to download this program. Here's a list of what I've done so far:

(
Windows 10
node -v => 14.13.0
npm -v => 6.14.8
)

1. Installed Rust (v.1.47.0)
2. `npm i korean-dictionary`
  -- this resulted in multiple errors telling me I needed Python (v2.7.15) and Visual Studio (2017) with some extensions.
3. I used `npm i --global --production windows-build-tools` to download both
4. I tried `npm i korean-dictionary` again and now this error happens:

```shell
if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  binding.cc
  win_delay_load_hook.cc
c:\users\jacob\apps\_test\koreandictionary\node_modules\nan\nan_converters_43_inl.h(22): error C2664: 'v8::Local<v8::Boolean> v8::Value::ToBoolean(v8::Isolate *) const': cannot convert argu
ment 1 from 'v8::Local<v8::Context>' to 'v8::Isolate *' (compiling source file ..\src\binding.cc) [C:\Users\Jacob\apps\_test\KoreanDictionary\node_modules\ref\build\binding.vcxproj]
  c:\users\jacob\apps\_test\koreandictionary\node_modules\nan\nan_converters_43_inl.h(22): note: No user-defined-conversion operator available that can perform this conversion, or the opera
  tor cannot be called (compiling source file ..\src\binding.cc)
c:\users\jacob\apps\_test\koreandictionary\node_modules\nan\nan_converters_43_inl.h(40): error C2664: 'bool v8::Value::BooleanValue(v8::Isolate *) const': cannot convert argument 1 from 'v8
::Local<v8::Context>' to 'v8::Isolate *' (compiling source file ..\src\binding.cc) [C:\Users\Jacob\apps\_test\KoreanDictionary\node_modules\ref\build\binding.vcxproj]
  c:\users\jacob\apps\_test\koreandictionary\node_modules\nan\nan_converters_43_inl.h(40): note: No user-defined-conversion operator available that can perform this conversion, or the opera
  tor cannot be called (compiling source file ..\src\binding.cc)
c:\users\jacob\apps\_test\koreandictionary\node_modules\nan\nan_implementation_12_inl.h(356): error C2660: 'v8::StringObject::New': function does not take 1 arguments (compiling source file
 ..\src\binding.cc) [C:\Users\Jacob\apps\_test\KoreanDictionary\node_modules\ref\build\binding.vcxproj]
  c:\users\jacob\appdata\local\node-gyp\cache\14.13.0\include\node\v8.h(5847): note: see declaration of 'v8::StringObject::New' (compiling source file ..\src\binding.cc)
c:\users\jacob\apps\_test\koreandictionary\node_modules\nan\nan_implementation_12_inl.h(356): error C2059: syntax error: ')' (compiling source file ..\src\binding.cc) [C:\Users\Jacob\apps\_
test\KoreanDictionary\node_modules\ref\build\binding.vcxproj]
c:\users\jacob\apps\_test\koreandictionary\node_modules\nan\nan_object_wrap.h(24): error C2039: 'IsNearDeath': is not a member of 'Nan::Persistent<v8::Object,v8::NonCopyablePersistentTraits
<T>>' [C:\Users\Jacob\apps\_test\KoreanDictionary\node_modules\ref\build\binding.vcxproj]
          with
          [
              T=v8::Object
          ] (compiling source file ..\src\binding.cc)
  c:\users\jacob\apps\_test\koreandictionary\node_modules\nan\nan.h(1920): note: see declaration of 'Nan::Persistent<v8::Object,v8::NonCopyablePersistentTraits<T>>'
          with
          [
              T=v8::Object
          ] (compiling source file ..\src\binding.cc)
c:\users\jacob\apps\_test\koreandictionary\node_modules\nan\nan_object_wrap.h(127): error C2039: 'IsNearDeath': is not a member of 'Nan::Persistent<v8::Object,v8::NonCopyablePersistentTrait
s<T>>' [C:\Users\Jacob\apps\_test\KoreanDictionary\node_modules\ref\build\binding.vcxproj]
          with
          [
              T=v8::Object
          ] (compiling source file ..\src\binding.cc)
  c:\users\jacob\apps\_test\koreandictionary\node_modules\nan\nan.h(1920): note: see declaration of 'Nan::Persistent<v8::Object,v8::NonCopyablePersistentTraits<T>>'
          with
          [
              T=v8::Object
          ] (compiling source file ..\src\binding.cc)
c:\users\jacob\apps\_test\koreandictionary\node_modules\ref\src\binding.cc(222): error C2660: 'v8::Value::BooleanValue': function does not take 0 arguments [C:\Users\Jacob\apps\_test\Korean
Dictionary\node_modules\ref\build\binding.vcxproj]
  c:\users\jacob\appdata\local\node-gyp\cache\14.13.0\include\node\v8.h(2858): note: see declaration of 'v8::Value::BooleanValue' (compiling source file ..\src\binding.cc)
c:\users\jacob\apps\_test\koreandictionary\node_modules\ref\src\binding.cc(253): error C2660: 'v8::Value::Uint32Value': function does not take 0 arguments [C:\Users\Jacob\apps\_test\KoreanD
ictionary\node_modules\ref\build\binding.vcxproj]
  c:\users\jacob\appdata\local\node-gyp\cache\14.13.0\include\node\v8.h(2866): note: see declaration of 'v8::Value::Uint32Value' (compiling source file ..\src\binding.cc)
c:\users\jacob\apps\_test\koreandictionary\node_modules\ref\src\binding.cc(360): error C2664: 'v8::String::Utf8Value::Utf8Value(const v8::String::Utf8Value &)': cannot convert argument 1 fr
om 'v8::Local<v8::Value>' to 'const v8::String::Utf8Value &' [C:\Users\Jacob\apps\_test\KoreanDictionary\node_modules\ref\build\binding.vcxproj]
  c:\users\jacob\apps\_test\koreandictionary\node_modules\ref\src\binding.cc(360): note: Reason: cannot convert from 'v8::Local<v8::Value>' to 'const v8::String::Utf8Value'
  c:\users\jacob\apps\_test\koreandictionary\node_modules\ref\src\binding.cc(360): note: No user-defined-conversion operator available that can perform this conversion, or the operator cann
  ot be called
c:\users\jacob\apps\_test\koreandictionary\node_modules\ref\src\binding.cc(447): error C2664: 'v8::String::Utf8Value::Utf8Value(const v8::String::Utf8Value &)': cannot convert argument 1 fr
om 'v8::Local<v8::Value>' to 'const v8::String::Utf8Value &' [C:\Users\Jacob\apps\_test\KoreanDictionary\node_modules\ref\build\binding.vcxproj]
  c:\users\jacob\apps\_test\koreandictionary\node_modules\ref\src\binding.cc(447): note: Reason: cannot convert from 'v8::Local<v8::Value>' to 'const v8::String::Utf8Value'
  c:\users\jacob\apps\_test\koreandictionary\node_modules\ref\src\binding.cc(447): note: No user-defined-conversion operator available that can perform this conversion, or the operator cann
  ot be called
c:\users\jacob\apps\_test\koreandictionary\node_modules\ref\src\binding.cc(521): error C2660: 'v8::Value::Uint32Value': function does not take 0 arguments [C:\Users\Jacob\apps\_test\KoreanD
ictionary\node_modules\ref\build\binding.vcxproj]
  c:\users\jacob\appdata\local\node-gyp\cache\14.13.0\include\node\v8.h(2866): note: see declaration of 'v8::Value::Uint32Value' (compiling source file ..\src\binding.cc)
c:\users\jacob\apps\_test\koreandictionary\node_modules\ref\src\binding.cc(550): error C2660: 'v8::Value::Uint32Value': function does not take 0 arguments [C:\Users\Jacob\apps\_test\KoreanD
ictionary\node_modules\ref\build\binding.vcxproj]
  c:\users\jacob\appdata\local\node-gyp\cache\14.13.0\include\node\v8.h(2866): note: see declaration of 'v8::Value::Uint32Value' (compiling source file ..\src\binding.cc)
c:\users\jacob\apps\_test\koreandictionary\node_modules\ref\src\binding.cc(582): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Users\Jacob\apps\_test\KoreanDi
ctionary\node_modules\ref\build\binding.vcxproj]
c:\users\jacob\apps\_test\koreandictionary\node_modules\ref\src\binding.cc(583): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Users\Jacob\apps\_test\KoreanDi
ctionary\node_modules\ref\build\binding.vcxproj]
c:\users\jacob\apps\_test\koreandictionary\node_modules\ref\src\binding.cc(584): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Users\Jacob\apps\_test\KoreanDi
ctionary\node_modules\ref\build\binding.vcxproj]
c:\users\jacob\apps\_test\koreandictionary\node_modules\ref\src\binding.cc(585): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Users\Jacob\apps\_test\KoreanDi
ctionary\node_modules\ref\build\binding.vcxproj]
c:\users\jacob\apps\_test\koreandictionary\node_modules\ref\src\binding.cc(586): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Users\Jacob\apps\_test\KoreanDi
ctionary\node_modules\ref\build\binding.vcxproj]
c:\users\jacob\apps\_test\koreandictionary\node_modules\ref\src\binding.cc(587): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Users\Jacob\apps\_test\KoreanDi
ctionary\node_modules\ref\build\binding.vcxproj]
c:\users\jacob\apps\_test\koreandictionary\node_modules\ref\src\binding.cc(588): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Users\Jacob\apps\_test\KoreanDi
ctionary\node_modules\ref\build\binding.vcxproj]
c:\users\jacob\apps\_test\koreandictionary\node_modules\ref\src\binding.cc(589): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Users\Jacob\apps\_test\KoreanDi
ctionary\node_modules\ref\build\binding.vcxproj]
c:\users\jacob\apps\_test\koreandictionary\node_modules\ref\src\binding.cc(590): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Users\Jacob\apps\_test\KoreanDi
ctionary\node_modules\ref\build\binding.vcxproj]
c:\users\jacob\apps\_test\koreandictionary\node_modules\ref\src\binding.cc(591): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Users\Jacob\apps\_test\KoreanDi
ctionary\node_modules\ref\build\binding.vcxproj]
c:\users\jacob\apps\_test\koreandictionary\node_modules\ref\src\binding.cc(593): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Users\Jacob\apps\_test\KoreanDi
ctionary\node_modules\ref\build\binding.vcxproj]
c:\users\jacob\apps\_test\koreandictionary\node_modules\ref\src\binding.cc(594): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Users\Jacob\apps\_test\KoreanDi
ctionary\node_modules\ref\build\binding.vcxproj]
c:\users\jacob\apps\_test\koreandictionary\node_modules\ref\src\binding.cc(595): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Users\Jacob\apps\_test\KoreanDi
ctionary\node_modules\ref\build\binding.vcxproj]
c:\users\jacob\apps\_test\koreandictionary\node_modules\ref\src\binding.cc(596): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Users\Jacob\apps\_test\KoreanDi
ctionary\node_modules\ref\build\binding.vcxproj]
c:\users\jacob\apps\_test\koreandictionary\node_modules\ref\src\binding.cc(597): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Users\Jacob\apps\_test\KoreanDi
ctionary\node_modules\ref\build\binding.vcxproj]
c:\users\jacob\apps\_test\koreandictionary\node_modules\ref\src\binding.cc(598): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Users\Jacob\apps\_test\KoreanDi
ctionary\node_modules\ref\build\binding.vcxproj]
c:\users\jacob\apps\_test\koreandictionary\node_modules\ref\src\binding.cc(599): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Users\Jacob\apps\_test\KoreanDi
ctionary\node_modules\ref\build\binding.vcxproj]
c:\users\jacob\apps\_test\koreandictionary\node_modules\ref\src\binding.cc(600): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Users\Jacob\apps\_test\KoreanDi
ctionary\node_modules\ref\build\binding.vcxproj]
c:\users\jacob\apps\_test\koreandictionary\node_modules\ref\src\binding.cc(601): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Users\Jacob\apps\_test\KoreanDi
ctionary\node_modules\ref\build\binding.vcxproj]
c:\users\jacob\apps\_test\koreandictionary\node_modules\ref\src\binding.cc(602): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Users\Jacob\apps\_test\KoreanDi
ctionary\node_modules\ref\build\binding.vcxproj]
c:\users\jacob\apps\_test\koreandictionary\node_modules\ref\src\binding.cc(603): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Users\Jacob\apps\_test\KoreanDi
ctionary\node_modules\ref\build\binding.vcxproj]
c:\users\jacob\apps\_test\koreandictionary\node_modules\ref\src\binding.cc(604): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Users\Jacob\apps\_test\KoreanDi
ctionary\node_modules\ref\build\binding.vcxproj]
c:\users\jacob\apps\_test\koreandictionary\node_modules\ref\src\binding.cc(605): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Users\Jacob\apps\_test\KoreanDi
ctionary\node_modules\ref\build\binding.vcxproj]
c:\users\jacob\apps\_test\koreandictionary\node_modules\ref\src\binding.cc(606): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Users\Jacob\apps\_test\KoreanDi
ctionary\node_modules\ref\build\binding.vcxproj]
c:\users\jacob\apps\_test\koreandictionary\node_modules\ref\src\binding.cc(608): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Users\Jacob\apps\_test\KoreanDi
ctionary\node_modules\ref\build\binding.vcxproj]
c:\users\jacob\apps\_test\koreandictionary\node_modules\ref\src\binding.cc(615): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Users\Jacob\apps\_test\KoreanDi
ctionary\node_modules\ref\build\binding.vcxproj]
c:\users\jacob\apps\_test\koreandictionary\node_modules\ref\src\binding.cc(616): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Users\Jacob\apps\_test\KoreanDi
ctionary\node_modules\ref\build\binding.vcxproj]
c:\users\jacob\apps\_test\koreandictionary\node_modules\ref\src\binding.cc(617): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Users\Jacob\apps\_test\KoreanDi
ctionary\node_modules\ref\build\binding.vcxproj]
c:\users\jacob\apps\_test\koreandictionary\node_modules\ref\src\binding.cc(618): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Users\Jacob\apps\_test\KoreanDi
ctionary\node_modules\ref\build\binding.vcxproj]
c:\users\jacob\apps\_test\koreandictionary\node_modules\ref\src\binding.cc(619): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Users\Jacob\apps\_test\KoreanDi
ctionary\node_modules\ref\build\binding.vcxproj]
c:\users\jacob\apps\_test\koreandictionary\node_modules\ref\src\binding.cc(620): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Users\Jacob\apps\_test\KoreanDi
ctionary\node_modules\ref\build\binding.vcxproj]
c:\users\jacob\apps\_test\koreandictionary\node_modules\ref\src\binding.cc(621): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Users\Jacob\apps\_test\KoreanDi
ctionary\node_modules\ref\build\binding.vcxproj]
c:\users\jacob\apps\_test\koreandictionary\node_modules\ref\src\binding.cc(622): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Users\Jacob\apps\_test\KoreanDi
ctionary\node_modules\ref\build\binding.vcxproj]
c:\users\jacob\apps\_test\koreandictionary\node_modules\ref\src\binding.cc(623): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Users\Jacob\apps\_test\KoreanDi
ctionary\node_modules\ref\build\binding.vcxproj]
c:\users\jacob\apps\_test\koreandictionary\node_modules\ref\src\binding.cc(624): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Users\Jacob\apps\_test\KoreanDi
ctionary\node_modules\ref\build\binding.vcxproj]
c:\users\jacob\apps\_test\koreandictionary\node_modules\ref\src\binding.cc(625): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Users\Jacob\apps\_test\KoreanDi
ctionary\node_modules\ref\build\binding.vcxproj]
c:\users\jacob\apps\_test\koreandictionary\node_modules\ref\src\binding.cc(626): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Users\Jacob\apps\_test\KoreanDi
ctionary\node_modules\ref\build\binding.vcxproj]
c:\users\jacob\apps\_test\koreandictionary\node_modules\ref\src\binding.cc(627): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Users\Jacob\apps\_test\KoreanDi
ctionary\node_modules\ref\build\binding.vcxproj]
c:\users\jacob\apps\_test\koreandictionary\node_modules\ref\src\binding.cc(628): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Users\Jacob\apps\_test\KoreanDi
ctionary\node_modules\ref\build\binding.vcxproj]
c:\users\jacob\apps\_test\koreandictionary\node_modules\ref\src\binding.cc(629): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Users\Jacob\apps\_test\KoreanDi
ctionary\node_modules\ref\build\binding.vcxproj]
c:\users\jacob\apps\_test\koreandictionary\node_modules\ref\src\binding.cc(630): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Users\Jacob\apps\_test\KoreanDi
ctionary\node_modules\ref\build\binding.vcxproj]
c:\users\jacob\apps\_test\koreandictionary\node_modules\ref\src\binding.cc(631): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Users\Jacob\apps\_test\KoreanDi
ctionary\node_modules\ref\build\binding.vcxproj]
c:\users\jacob\apps\_test\koreandictionary\node_modules\ref\src\binding.cc(632): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Users\Jacob\apps\_test\KoreanDi
ctionary\node_modules\ref\build\binding.vcxproj]
c:\users\jacob\apps\_test\koreandictionary\node_modules\ref\src\binding.cc(633): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Users\Jacob\apps\_test\KoreanDi
ctionary\node_modules\ref\build\binding.vcxproj]
c:\users\jacob\apps\_test\koreandictionary\node_modules\ref\src\binding.cc(634): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Users\Jacob\apps\_test\KoreanDi
ctionary\node_modules\ref\build\binding.vcxproj]
c:\users\jacob\apps\_test\koreandictionary\node_modules\ref\src\binding.cc(635): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Users\Jacob\apps\_test\KoreanDi
ctionary\node_modules\ref\build\binding.vcxproj]
c:\users\jacob\apps\_test\koreandictionary\node_modules\ref\src\binding.cc(636): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Users\Jacob\apps\_test\KoreanDi
ctionary\node_modules\ref\build\binding.vcxproj]
c:\users\jacob\apps\_test\koreandictionary\node_modules\ref\src\binding.cc(637): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Users\Jacob\apps\_test\KoreanDi
ctionary\node_modules\ref\build\binding.vcxproj]
c:\users\jacob\apps\_test\koreandictionary\node_modules\ref\src\binding.cc(638): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Users\Jacob\apps\_test\KoreanDi
ctionary\node_modules\ref\build\binding.vcxproj]
c:\users\jacob\apps\_test\koreandictionary\node_modules\ref\src\binding.cc(641): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Users\Jacob\apps\_test\KoreanDi
ctionary\node_modules\ref\build\binding.vcxproj]
c:\users\jacob\apps\_test\koreandictionary\node_modules\ref\src\binding.cc(642): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Users\Jacob\apps\_test\KoreanDi
ctionary\node_modules\ref\build\binding.vcxproj]
c:\users\jacob\apps\_test\koreandictionary\node_modules\ref\src\binding.cc(643): warning C4996: 'Nan::ForceSet': was declared deprecated [C:\Users\Jacob\apps\_test\KoreanDictionary\node_mod
ules\ref\build\binding.vcxproj]
  c:\users\jacob\apps\_test\koreandictionary\node_modules\nan\nan_maybe_43_inl.h(130): note: see declaration of 'Nan::ForceSet'
c:\users\jacob\apps\_test\koreandictionary\node_modules\ref\src\binding.cc(644): warning C4996: 'Nan::ForceSet': was declared deprecated [C:\Users\Jacob\apps\_test\KoreanDictionary\node_mod
ules\ref\build\binding.vcxproj]
  c:\users\jacob\apps\_test\koreandictionary\node_modules\nan\nan_maybe_43_inl.h(130): note: see declaration of 'Nan::ForceSet'
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Jacob\apps\_test\KoreanDictionary\node_modules\ref
gyp ERR! node -v v14.13.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ref@1.3.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ref@1.3.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Jacob\AppData\Roaming\npm-cache\_logs\2020-10-09T16_51_36_601Z-debug.log
```

Google isn't helping much with this, unfortunately.
Is this program still working? If it is, am I doing anything wrong to install and use it?
Thanks for any help!

**Comment by jacoblockett** [comment]
Closing due to no response from owner. Feel free to reopen if you decide you want to take a look at it, but it was probably a mistake on my end.
